---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
      - deps/github-actions
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - deps/npm
    groups:
      javascript-deps:
        applies-to: version-updates
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"
